version: "3.7"
services:
  nginx:
    image: nginx:1.14.1-alpine
    restart: always
    volumes:
      - ./nginx/conf:/etc/nginx/conf
      - ./nginx/log:/var/log/nginx
      - ./nginx/modules/:/etc/nginx/modules
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      TZ: Asia/Tokyo
    ports:
      - "80:80"
    networks:
      - app

networks:
  app:
    name: app
