version: "3"
services:
  app:
    image: golang:1.10
    volumes:
      - ../app:/go/src/app
    command: go run /go/src/app/main.go
    restart: always
    environment:
      TZ: Asia/Tokyo
      PORT: 8080
      DB_HOST: app-mysql
      DB_PORT: 3306
      DB_USER: root
      DB_NAME: app
    depends_on:
      - mysql
    links:
      - mysql:app-mysql

  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/lib:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      TZ: Asia/Tokyo
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
    restart: always

  nginx:
    image: nginx:1.14
    restart: always
    volumes:
      - ./nginx/conf:/etc/nginx/conf
      - ./nginx/log:/var/log/nginx
      - ./nginx/modules/:/etc/nginx/modules
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../static:/static
    environment:
      TZ: Asia/Tokyo
    ports:
      - "80:80"
    depends_on:
      - app
    links:
      - app:app
